epc: ansi2knr.c File Reference
ansi2knr.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <string.h>
Macros
#define is_ascii(c) 1
#define is_space(c) (is_ascii(c) && isspace(c))
#define is_alpha(c) (is_ascii(c) && isalpha(c))
#define is_alnum(c) (is_ascii(c) && isalnum(c))
#define isidchar(ch) (is_alnum(ch) || (ch) == '_')
#define isidfirstchar(ch) (is_alpha(ch) || (ch) == '_')
#define bufsize 5000 /* arbitrary size */
Functions
char * malloc ()
int free ()
char * skipspace ()
int writeblanks ()
int test1 ()
int convert1 ()
int main (int argc, argv)
char * skipspace (char *p, int dir)
int writeblanks (char *start, char *end)
int test1 (char *buf)
int convert1 (char *buf, FILE *out, int header, int convert_varargs)
Macro Definition Documentation
bufsize
#define bufsize 5000 /* arbitrary size */
is_alnum
#define is_alnum (c) (is_ascii(c) && isalnum(c))
Definition at line 172 of file ansi2knr.c.
is_alpha
#define is_alpha (c) (is_ascii(c) && isalpha(c))
Definition at line 171 of file ansi2knr.c.
is_ascii
#define is_ascii (c) 1
Definition at line 165 of file ansi2knr.c.
is_space
#define is_space (c) (is_ascii(c) && isspace(c))
Definition at line 170 of file ansi2knr.c.
isidchar
#define isidchar (ch) (is_alnum(ch) || (ch) == '_')
Definition at line 175 of file ansi2knr.c.
isidfirstchar
#define isidfirstchar (ch) (is_alpha(ch) || (ch) == '_')
Definition at line 176 of file ansi2knr.c.
Function Documentation
convert1() [1/2]
int convert1 ()
Referenced by main().
convert1() [2/2]
int convert1 (char * buf, FILE * out, int header, int convert_varargs)
Definition at line 461 of file ansi2knr.c.
 {
   char *endfn;
   register char *p;
   /*
    * The breaks table contains pointers to the beginning and end
    * of each argument.
    */
   char **breaks;
   unsigned num_breaks = 2;      /* for testing */
   char **btop;
   char **bp;
   char **ap;
   char *vararg = 0;
   /* Pre-ANSI implementations don't agree on whether strchr */
   /* is called strchr or index, so we open-code it here. */
   for (endfn = buf; *(endfn++) != '(';)
     ;
 top:p = endfn;
   breaks = (char **) malloc (sizeof (char *) * num_breaks * 2);
   if (breaks == 0)
     {                           /* Couldn't allocate break table, give up */
       fprintf (stderr, "Unable to allocate break table!\n");
       fputs (buf, out);
       return -1;
     }
   btop = breaks + num_breaks * 2 - 2;
   bp = breaks;
   /* Parse the argument list */
   do
     {
       int level = 0;
       char *lp = NULL;
       char *rp;
       char *end = NULL;
       if (bp >= btop)
         {                       /* Filled up break table. */
           /* Allocate a bigger one and start over. */
           free ((char *) breaks);
           num_breaks <<= 1;
           goto top;
         }
       *bp++ = p;
       /* Find the end of the argument */
       for (; end == NULL; p++)
         {
           switch (*p)
             {
             case ',':
               if (!level)
                 end = p;
               break;
             case '(':
               if (!level)
                 lp = p;
               level++;
               break;
             case ')':
               if (--level < 0)
                 end = p;
               else
                 rp = p;
               break;
             case '/':
               p = skipspace (p, 1) - 1;
               break;
             default:
               ;
             }
         }
       /* Erase any embedded prototype parameters. */
       if (lp)
         writeblanks (lp + 1, rp);
       p--;                      /* back up over terminator */
       /* Find the name being declared. */
       /* This is complicated because of procedure and */
       /* array modifiers. */
       for (;;)
         {
           p = skipspace (p - 1, -1);
           switch (*p)
             {
             case ']':           /* skip array dimension(s) */
             case ')':           /* skip procedure args OR name */
               {
                 int level = 1;
                 while (level)
                   switch (*--p)
                     {
                     case ']':
                     case ')':
                       level++;
                       break;
                     case '[':
                     case '(':
                       level--;
                       break;
                     case '/':
                       p = skipspace (p, -1) + 1;
                       break;
                     default:;
                     }
               }
               if (*p == '(' && *skipspace (p + 1, 1) == '*')
                 {               /* We found the name being declared */
                   while (!isidfirstchar (*p))
                     p = skipspace (p, 1) + 1;
                   goto found;
                 }
               break;
             default:
               goto found;
             }
         }
     found:if (*p == '.' && p[-1] == '.' && p[-2] == '.')
         {
           if (convert_varargs)
             {
               *bp++ = "va_alist";
               vararg = p - 2;
             }
           else
             {
               p++;
               if (bp == breaks + 1)     /* sole argument */
                 writeblanks (breaks[0], p);
               else
                 writeblanks (bp[-1] - 1, p);
               bp--;
             }
         }
       else
         {
           while (isidchar (*p))
             p--;
           *bp++ = p + 1;
         }
       p = end;
     }
   while (*p++ == ',');
   *bp = p;
   /* Make a special check for 'void' arglist */
   if (bp == breaks + 2)
     {
       p = skipspace (breaks[0], 1);
       if (!strncmp (p, "void", 4))
         {
           p = skipspace (p + 4, 1);
           if (p == breaks[2] - 1)
             {
               bp = breaks;      /* yup, pretend arglist is empty */
               writeblanks (breaks[0], p + 1);
             }
         }
     }
   /* Put out the function name and left parenthesis. */
   p = buf;
   while (p != endfn)
     putc (*p, out), p++;
   /* Put out the declaration. */
   if (header)
     {
       fputs (");", out);
       for (p = breaks[0]; *p; p++)
         if (*p == '\r' || *p == '\n')
           putc (*p, out);
     }
   else
     {
       for (ap = breaks + 1; ap < bp; ap += 2)
         {
           p = *ap;
           while (isidchar (*p))
             putc (*p, out), p++;
           if (ap < bp - 1)
             fputs (", ", out);
         }
       fputs (")  ", out);
       /* Put out the argument declarations */
       for (ap = breaks + 2; ap <= bp; ap += 2)
         (*ap)[-1] = ';';
       if (vararg != 0)
         {
           *vararg = 0;
           fputs (breaks[0], out);       /* any prior args */
           fputs ("va_dcl", out);        /* the final arg */
           fputs (bp[0], out);
         }
       else
         fputs (breaks[0], out);
     }
   free ((char *) breaks);
   return 0;
 }
References free(), isidchar, isidfirstchar, malloc(), skipspace(), and writeblanks().
free()
int free ()
Referenced by convert1(), epc__done(), epc__set_logon(), epc__set_pipe(), epc__xml_done(), and main().
main()
int main (int argc, argv)
Definition at line 186 of file ansi2knr.c.
 {
   FILE *in = stdin;
   FILE *out = stdout;
   char *filename = 0;
 #define bufsize 5000            /* arbitrary size */
   char *buf;
   char *line;
   char *more;
   char *usage =
     "Usage: ansi2knr [--filename FILENAME] [INPUT_FILE [OUTPUT_FILE]]\n";
   /*
    * In previous versions, ansi2knr recognized a --varargs switch.
    * If this switch was supplied, ansi2knr would attempt to convert
    * a ... argument to va_alist and va_dcl; if this switch was not
    * supplied, ansi2knr would simply drop any such arguments.
    * Now, ansi2knr always does this conversion, and we only
    * check for this switch for backward compatibility.
    */
   int convert_varargs = 1;
   while (argc > 1 && argv[1][0] == '-')
     {
       if (!strcmp (argv[1], "--varargs"))
         {
           convert_varargs = 1;
           argc--;
           argv++;
           continue;
         }
       if (!strcmp (argv[1], "--filename") && argc > 2)
         {
           filename = argv[2];
           argc -= 2;
           argv += 2;
           continue;
         }
       fprintf (stderr, "Unrecognized switch: %s\n", argv[1]);
       fprintf (stderr, usage);
       exit (1);
     }
   switch (argc)
     {
     default:
       fprintf (stderr, usage);
       exit (0);
     case 3:
       out = fopen (argv[2], "w");
       if (out == NULL)
         {
           fprintf (stderr, "Cannot open output file %s\n", argv[2]);
           exit (1);
         }
       /* falls through */
     case 2:
       in = fopen (argv[1], "r");
       if (in == NULL)
         {
           fprintf (stderr, "Cannot open input file %s\n", argv[1]);
           exit (1);
         }
       if (filename == 0)
         filename = argv[1];
       /* falls through */
     case 1:
       break;
     }
   if (filename)
     fprintf (out, "#line 1 \"%s\"\n", filename);
   buf = malloc (bufsize);
   line = buf;
   while (fgets (line, (unsigned) (buf + bufsize - line), in) != NULL)
     {
     test:line += strlen (line);
       switch (test1 (buf))
         {
         case 2:         /* a function header */
           convert1 (buf, out, 1, convert_varargs);
           break;
         case 1:         /* a function */
           /* Check for a { at the start of the next line. */
           more = ++line;
         f:if (line >= buf + (bufsize - 1))      /* overflow check */
             goto wl;
           if (fgets (line, (unsigned) (buf + bufsize - line), in) == NULL)
             goto wl;
           switch (*skipspace (more, 1))
             {
             case '{':
               /* Definitely a function header. */
               convert1 (buf, out, 0, convert_varargs);
               fputs (more, out);
               break;
             case 0:
               /* The next line was blank or a comment: */
               /* keep scanning for a non-comment. */
               line += strlen (line);
               goto f;
             default:
               /* buf isn't a function header, but */
               /* more might be. */
               fputs (buf, out);
               strcpy (buf, more);
               line = buf;
               goto test;
             }
           break;
         case -1:                /* maybe the start of a function */
           if (line != buf + (bufsize - 1))      /* overflow check */
             continue;
           /* falls through */
         default:                /* not a function */
         wl:fputs (buf, out);
           break;
         }
       line = buf;
     }
   if (line != buf)
     fputs (buf, out);
   free (buf);
   if (out != stdout)
     fclose (out);
   if (in != stdin)
     fclose (in);
   return 0;
 }
References bufsize, convert1(), free(), malloc(), skipspace(), and test1().
malloc()
char* malloc ()
Referenced by convert1(), epc__init(), and main().
skipspace() [1/2]
char* skipspace ()
Referenced by convert1(), main(), and test1().
skipspace() [2/2]
char* skipspace (char * p, int dir)
Definition at line 317 of file ansi2knr.c.
 {
   for (;;)
     {
       while (is_space (*p))
         p += dir;
       if (!(*p == '/' && p[dir] == '*'))
         break;
       p += dir;
       p += dir;
       while (!(*p == '*' && p[dir] == '/'))
         {
           if (*p == 0)
             return p;           /* multi-line comment?? */
           p += dir;
         }
       p += dir;
       p += dir;
     }
   return p;
 }
References is_space.
test1() [1/2]
int test1 ()
Referenced by main().
test1() [2/2]
int test1 (char * buf)
Definition at line 371 of file ansi2knr.c.
 {
   register char *p = buf;
   char *bend;
   char *endfn;
   int contin;
   if (!isidfirstchar (*p))
     return 0;                   /* no name at left margin */
   bend = skipspace (buf + strlen (buf) - 1, -1);
   switch (*bend)
     {
     case ';':
       contin = 0 /*2 */ ;
       break;
     case ')':
       contin = 1;
       break;
     case '{':
       return 0;                 /* not a function */
     case '}':
       return 0;                 /* not a function */
     default:
       contin = -1;
     }
   while (isidchar (*p))
     p++;
   endfn = p;
   p = skipspace (p, 1);
   if (*p++ != '(')
     return 0;                   /* not a function */
   p = skipspace (p, 1);
   if (*p == ')')
     return 0;                   /* no parameters */
   /* Check that the apparent function name isn't a keyword. */
   /* We only need to check for keywords that could be followed */
   /* by a left parenthesis (which, unfortunately, is most of them). */
   {
     static char *words[] = { "asm", "auto", "case", "char", "const", "double",
       "extern", "float", "for", "if", "int", "long",
       "register", "return", "short", "signed", "sizeof",
       "static", "switch", "typedef", "unsigned",
       "void", "volatile", "while", 0
     };
     char **key = words;
     char *kp;
     int len = endfn - buf;
     while ((kp = *key) != 0)
       {
         if (strlen (kp) == len && !strncmp (kp, buf, len))
           return 0;             /* name is a keyword */
         key++;
       }
   }
   {
     char *id = p;
     int len;
     /*
      * Check for identifier1(identifier2) and not
      * identifier1(void).
      */
     while (isidchar (*p))
       p++;
     len = p - id;
     p = skipspace (p, 1);
     if (*p == ')' && (len != 4 || strncmp (id, "void", 4)))
       return 0;                 /* not a function */
   }
   /*
    * If the last significant character was a ), we need to count
    * parentheses, because it might be part of a formal parameter
    * that is a procedure.
    */
   if (contin > 0)
     {
       int level = 0;
       for (p = skipspace (buf, 1); *p; p = skipspace (p + 1, 1))
         level += (*p == '(' ? 1 : *p == ')' ? -1 : 0);
       if (level > 0)
         contin = -1;
     }
   return contin;
 }
References isidchar, isidfirstchar, and skipspace().
writeblanks() [1/2]
int writeblanks ()
Referenced by convert1().
writeblanks() [2/2]
int writeblanks (char * start, char * end)
Definition at line 346 of file ansi2knr.c.
 {
   char *p;
   for (p = start; p < end; p++)
     if (*p != '\r' && *p != '\n')
       *p = ' ';
   return 0;
 }