epc: epc.h File Reference
epc.h File Reference
#include <epc_defs.h>
Typedefs
typedef void(* epc__handle_interrupt_t) (epc__info_t *)
Functions
void epc__set_signal_handlers (const int idx)
void epc__reset_signal_handlers (const int idx)
void epc__call_print (epc__call_t *call)
void epc__function_print (epc__function_t *function)
int epc__get_signo (void)
void epc__lookup_interface (const char *interface_name, epc__info_t *epc__info, epc__call_t *epc__call)
Lookup the interface in the list of interfaces.
void epc__lookup_function (const char *function_name, epc__info_t *epc__info, epc__call_t *epc__call)
Lookup the function in the list of functions of an interface.
void epc__set_handle_interrupt (epc__handle_interrupt_t handle_interrupt, epc__info_t *epc__info)
epc__error_t epc__main (int argc, char **argv, epc__interface_t *)
Start the EPC for one interface.
epc__error_t epc__list_main (int argc, char **argv, epc__interface_t *,...)
Start the EPC for one or more interfaces.
char * epc__get_error_str (epc__error_t err)
epc__info_t * epc__init (void)
void epc__done (epc__info_t *epc__info)
epc__error_t epc__set_logon (epc__info_t *epc__info, char *logon)
epc__error_t epc__set_pipe (epc__info_t *epc__info, char *pipe)
void epc__chk_parameter (epc__parameter_t *parameter)
void epc__chk_function (epc__function_t *function)
void epc__chk_interface (epc__interface_t *interface)
epc__error_t epc__add_interface (epc__info_t *epc__info, epc__interface_t *interface)
long epc__handle_request (epc__info_t *epc__info, epc__call_t *call, epc__error_t(*recv_request)(epc__info_t *, epc__call_t *), epc__error_t(*send_response)(epc__info_t *, epc__call_t *))
epc__error_t epc__handle_requests (epc__info_t *epc__info, epc__error_t(*recv_request)(epc__info_t *, epc__call_t *), epc__error_t(*send_response)(epc__info_t *, epc__call_t *))
void epc__abort (char *msg)
epc__error_t epc__connect (epc__info_t *epc__info)
epc__error_t epc__interrupt (epc__info_t *epc__info)
epc__error_t epc__disconnect (epc__info_t *epc__info)
epc__error_t epc__recv_request_pipe (epc__info_t *epc__info, epc__call_t *epc__call)
epc__error_t epc__send_response_pipe (epc__info_t *epc__info, epc__call_t *epc__call)
Typedef Documentation
epc__handle_interrupt_t
typedef void(* epc__handle_interrupt_t) (epc__info_t *)
Definition at line 11 of file epc.h.
Function Documentation
epc__abort()
void epc__abort (char * msg)
epc__add_interface()
epc__error_t epc__add_interface (epc__info_t * epc__info, epc__interface_t * interface)
Definition at line 708 of file epc_lib.c.
 {
   epc__error_t status = OK;
   DBUG_ENTER ("epc__add_interface");
   epc__chk_interface (interface);
   DBUG_PRINT ("input", ("epc__info: %p; interface: %s", (void *) epc__info, interface->name));
   if (epc__info == NULL)
     {
       status = MEMORY_ERROR;
     }
   else
     {
       epc__info->num_interfaces++;
       epc__info->interfaces =
         (epc__interface_t **)
         realloc ((void *) epc__info->interfaces,
                  (size_t) (epc__info->num_interfaces *
                            sizeof (epc__interface_t **)));
       if (epc__info->interfaces == NULL)
         {
           epc__info->num_interfaces--;
           status = MEMORY_ERROR;
         }
       else
         {
           dword_t fnr, pnr;
           epc__info->interfaces[epc__info->num_interfaces - 1] = interface;
           /* sort the functions */
           qsort (interface->functions,
                  (size_t) interface->num_functions,
                  sizeof (interface->functions[0]), epc__cmp_function);
           /* sort the interfaces */
           qsort (epc__info->interfaces,
                  (size_t) epc__info->num_interfaces,
                  sizeof (epc__info->interfaces[0]), epc__cmp_interface);
           /* allocate memory for the parameters */
           for (fnr = 0; fnr < interface->num_functions; fnr++)
             for (pnr = 0; pnr < interface->functions[fnr].num_parameters;
                  pnr++)
               {
                 size_t size = 0;
                 switch (interface->functions[fnr].parameters[pnr].type)
                   {
                   case C_STRING:
                   case C_XML:
                   case C_DATE:
                   case C_INT:
                   case C_LONG:
                   case C_FLOAT:
                   case C_DOUBLE:
                     size =
                       (size_t) interface->functions[fnr].parameters[pnr].size;
                     break;
                   case C_VOID:
                     continue;
                   default:
                     assert (interface->functions[fnr].parameters[pnr].type >=
                             C_DATATYPE_MIN
                             && interface->functions[fnr].parameters[pnr].
                             type <= C_DATATYPE_MAX);
                   }
                 if ((interface->functions[fnr].parameters[pnr].data =
                      malloc (size)) == NULL)
                   {
                     status = MEMORY_ERROR;
                     break;
                   }
               }
         }
     }
   DBUG_PRINT ("output", ("status: %d", (int) status));
   DBUG_LEAVE ();
   return (status);
 }
References epc__chk_interface(), epc__interface::functions, epc__info::interfaces, MEMORY_ERROR, epc__interface::name, epc__interface::num_functions, epc__info::num_interfaces, and OK.
epc__call_print()
void epc__call_print (epc__call_t * call)
Definition at line 473 of file epc_lib.c.
 {
   DBUG_ENTER ("epc__call_print");
   DBUG_PRINT ("input", ("msg info: '%s'; protocol: %c", call->msg_info, EPC__CALL_PROTOCOL(call)));
   DBUG_PRINT ("input",
               ("interface name: '%s'; function: %p",
                (call != NULL && call->interface != NULL
                 && call->interface->name !=
                 NULL ? call->interface->name : "(null)"),
                (void*) call->function));
   if (call->function != NULL)
     {
       epc__function_print(call->function);
     }
   DBUG_PRINT ("input",
               ("status: %ld; error code: %ld", (long) call->epc__error,
                (long) call->errcode));
   DBUG_LEAVE ();
 }
References EPC__CALL_PROTOCOL, epc__call::epc__error, epc__function_print(), epc__call::errcode, epc__call::function, epc__call::interface, epc__call::msg_info, and epc__interface::name.
epc__chk_function()
void epc__chk_function (epc__function_t * function)
Definition at line 679 of file epc_lib.c.
 {
   dword_t nr;
   assert(function != NULL);
   assert(function->name != NULL);
   assert(function->oneway == 0 || function->oneway == 1);
   assert(function->num_parameters >= 0);
   for (nr = 0; nr < function->num_parameters; nr++)
     {
       epc__chk_parameter(&function->parameters[nr]);
     }
 }
References epc__chk_parameter().
Referenced by epc__chk_interface().
epc__chk_interface()
void epc__chk_interface (epc__interface_t * interface)
Definition at line 694 of file epc_lib.c.
 {
   dword_t nr;
   assert(interface != NULL);
   assert(interface->name != NULL);
   assert(interface->num_functions > 0);
   for (nr = 0; nr < interface->num_functions; nr++)
     {
       epc__chk_function(&interface->functions[nr]);
     }
 }
References epc__chk_function(), epc__interface::functions, epc__interface::name, and epc__interface::num_functions.
Referenced by epc__add_interface().
epc__chk_parameter()
void epc__chk_parameter (epc__parameter_t * parameter)
Definition at line 669 of file epc_lib.c.
 {
   assert(parameter != NULL);
   assert(parameter->name != NULL);
   assert(parameter->mode >= C_PARAMETER_MODE_MIN && parameter->mode <= C_PARAMETER_MODE_MAX);
   assert(parameter->type >= C_DATATYPE_MIN && parameter->type <= C_DATATYPE_MAX);
   assert(parameter->size >= 0);
 }
References C_DATATYPE_MAX, C_DATATYPE_MIN, C_PARAMETER_MODE_MAX, C_PARAMETER_MODE_MIN, epc__parameter::mode, epc__parameter::name, epc__parameter::size, and epc__parameter::type.
Referenced by epc__chk_function().
epc__connect()
epc__error_t epc__connect (epc__info_t * epc__info)
epc__disconnect()
epc__error_t epc__disconnect (epc__info_t * epc__info)
epc__done()
void epc__done (epc__info_t * epc__info)
Definition at line 619 of file epc_lib.c.
 {
   DBUG_ENTER ("epc__done");
   DBUG_PRINT ("input", ("epc__info: %p", epc__info));
 #ifndef XML_OFF
   (void) epc__xml_done (epc__info);
 #endif
   if (epc__info->sqlca != NULL)
     free (epc__info->sqlca);
   if (epc__info->interfaces != NULL)
     {
       dword_t inr, fnr, pnr;
       for (inr = 0; inr < epc__info->num_interfaces; inr++)
         {
           epc__interface_t *interface = epc__info->interfaces[inr];
           /* free memory for the parameters */
           for (fnr = 0; fnr < interface->num_functions; fnr++)
             for (pnr = 0; pnr < interface->functions[fnr].num_parameters;
                  pnr++)
               {
                 /* detected by dmalloc */
                 if (interface->functions[fnr].parameters[pnr].data != NULL) {
                   free (interface->functions[fnr].parameters[pnr].data);
                   interface->functions[fnr].parameters[pnr].data = NULL;
                 }
               }
         }
       free (epc__info->interfaces);
     }
   /* not freeing epc__info->logon detected by dmalloc */
   if (epc__info->logon != NULL)
     free(epc__info->logon);
   if (epc__info->pipe != NULL)
     free(epc__info->pipe);
   free (epc__info);
   DBUG_LEAVE ();
 }
References epc__xml_done(), free(), epc__info::interfaces, epc__info::logon, epc__info::num_interfaces, epc__info::pipe, and epc__info::sqlca.
epc__function_print()
void epc__function_print (epc__function_t * function)
Definition at line 497 of file epc_lib.c.
 {
   dword_t nr;
   DBUG_ENTER ("epc__function_print");
   DBUG_PRINT ("input", ("name: '%s'; oneway: %ld; # parameters: %ld",
                         function->name, function->oneway, function->num_parameters));
   for (nr = 0L; nr < function->num_parameters; nr++)
     {
       DBUG_PRINT ("input",
                   ("parameter[%ld]: name: %s; mode: %d; type: %d; size: %ld",
                    nr,
                    function->parameters[nr].name,
                    function->parameters[nr].mode,
                    function->parameters[nr].type,
                    function->parameters[nr].size));
     }
   DBUG_LEAVE ();
 }
Referenced by epc__call_print().
epc__get_error_str()
char* epc__get_error_str (epc__error_t err)
Definition at line 540 of file epc_lib.c.
 {
   switch (err)
     {
     case OK:
       return "OK";
     case MSG_TIMED_OUT:
       return "MSG_TIMED_OUT";
     case MSG_TOO_BIG:
       return "MSG_TOO_BIG";
     case MSG_INTERRUPTED:
       return "MSG_INTERRUPTED";
     case RECEIVE_ERROR:
       return "RECEIVE_ERROR";
     case EXEC_ERROR:
       return "EXEC_ERROR";
     case PARSE_ERROR:
       return "PARSE_ERROR";
     case MEMORY_ERROR:
       return "MEMORY_ERROR";
     case DATATYPE_UNKNOWN:
       return "DATATYPE_UNKNOWN";
     case FUNCTION_UNKNOWN:
       return "FUNCTION_UNKNOWN";
     case PARAMETER_UNKNOWN:
       return "PARAMETER_UNKNOWN";
     case INTERFACE_UNKNOWN:
       return "INTERFACE_UNKNOWN";
     case PARAMETER_MODE_UNKNOWN:
       return "PARAMETER_MODE_UNKNOWN";
     case SEND_ERROR:
       return "SEND_ERROR";
     case CONNECT_ERROR:
       return "CONNECT_ERROR";
     case DISCONNECT_ERROR:
       return "DISCONNECT_ERROR";
     default:
       return "Unknown error";
     }
 }
References CONNECT_ERROR, DATATYPE_UNKNOWN, DISCONNECT_ERROR, EXEC_ERROR, FUNCTION_UNKNOWN, INTERFACE_UNKNOWN, MEMORY_ERROR, MSG_INTERRUPTED, MSG_TIMED_OUT, MSG_TOO_BIG, OK, PARAMETER_MODE_UNKNOWN, PARAMETER_UNKNOWN, PARSE_ERROR, RECEIVE_ERROR, and SEND_ERROR.
epc__get_signo()
int epc__get_signo (void)
Definition at line 1631 of file epc_lib.c.
 {
   return G_signo;
 }
epc__handle_request()
long epc__handle_request (epc__info_t * epc__info, epc__call_t * call, epc__error_t(*)(epc__info_t *, epc__call_t *) recv_request, epc__error_t(*)(epc__info_t *, epc__call_t *) send_response)
Definition at line 1447 of file epc_lib.c.
 {
   long retval = -1L;
   DBUG_ENTER ("epc__handle_request");
   DBUG_PRINT ("input", ("epc__info: %p", (void *) epc__info));
   do
     {
       /* receive the request */
       (void) (*recv_request) (epc__info, epc__call);
       /* do the call */
       if (epc__call->epc__error == OK)
         {
           (void) epc__exec_call (epc__info, epc__call);
         }
       /* construct the response when oneway is equal to 0 (no function counts
          too since we must report back the error) */
       if (!(epc__call->function != NULL && epc__call->function->oneway != 0))
         {
           switch (EPC__CALL_PROTOCOL(epc__call))
             {
             case PROTOCOL_NATIVE:
             case PROTOCOL_SOAP:
             case PROTOCOL_XMLRPC:
               switch (EPC__CALL_PROTOCOL(epc__call))
                 {
                 case PROTOCOL_NATIVE:
                   epc__response_native(epc__call);
                   break;
                 case PROTOCOL_SOAP:
                   epc__response_soap(epc__call);
                   break;
                 case PROTOCOL_XMLRPC:
                   epc__response_xmlrpc(epc__call);
                   break;
                 default:
                   assert(EPC__CALL_PROTOCOL(epc__call) >= PROTOCOL_MIN && EPC__CALL_PROTOCOL(epc__call) <= PROTOCOL_MAX);
                   break;
                 }
               DBUG_PRINT ("info", ("msg_response: %s", epc__call->msg_response));
               (void) (*send_response) (epc__info, epc__call);
               break;
             default:
               break;
             }
         }
       if (epc__call->epc__error != OK)
         break;
       retval = 0L;
     }
   while (0);                    /* loop is used only to be able to break out earlier */
   /* GJP 18-10-2004 Do not know why dbms_pipe errors should be ignored */
   /*#define OBSOLETE 1 */
 #ifdef OBSOLETE
   switch (epc__call->epc__error)
     {
     case MSG_TIMED_OUT:
     case RECEIVE_ERROR:
     case SEND_ERROR:
     case OK:
       switch (epc__call->errcode)
         {
         case -6556:             /* the pipe is empty, cannot fulfill the unpack_message request */
         case -6558:             /* buffer in dbms_pipe package is full. No more items allowed */
         case -6559:             /* wrong datatype requested, string, actual datatype is string */
         case 0:
           retval = 0;
           break;
         default:
           break;
         }
       break;
     default:
       break;
     }
 #endif
   DBUG_PRINT ("output",
               ("retval: %ld; error code: %ld; epc status: %s",
                retval, (long) epc__call->errcode,
                epc__get_error_str (epc__call->epc__error)));
   DBUG_LEAVE ();
   return retval;
 }
References epc__call::epc__error, and OK.
epc__handle_requests()
epc__error_t epc__handle_requests (epc__info_t * epc__info, epc__error_t(*)(epc__info_t *, epc__call_t *) recv_request, epc__error_t(*)(epc__info_t *, epc__call_t *) send_response)
Definition at line 1560 of file epc_lib.c.
 {
   epc__call_t epc__call = EPC__CALL_INIT;
   DBUG_ENTER ("epc__handle_requests");
   DBUG_PRINT ("input", ("epc__info: %p", (void *) epc__info));
   for (epc__call.errcode = 0; G_signo == 0; epc__call.errcode = 0)
     {
       if (epc__handle_request
           (epc__info, &epc__call, recv_request, send_response) != 0)
         break;
     }
   DBUG_PRINT ("output",
               ("error code: %ld; epc status: %s",
                (long) epc__call.errcode,
                epc__get_error_str (epc__call.epc__error)));
   DBUG_LEAVE ();
   return epc__call.epc__error;
 }
References EPC__CALL_INIT, and epc__call::errcode.
epc__init()
epc__info_t* epc__init (void)
Definition at line 582 of file epc_lib.c.
 {
   epc__info_t *epc__info = NULL;
   DBUG_ENTER ("epc__init");
   epc__info = (epc__info_t *) malloc (sizeof (epc__info_t));
   if (epc__info == NULL)
     {
       exit (EXIT_FAILURE);
     }
   epc__info->logon = NULL;
   epc__info->connected = 0;
   epc__info->pipe = NULL;
   epc__info->num_interfaces = 0;
   epc__info->interfaces = NULL;
   epc__info->sqlca = NULL;
 #ifndef XML_OFF
   epc__info->xml_info = NULL;
 #endif
   epc__info->purge_pipe = 0;
   epc__info->interrupt = 0;
   epc__info->program = NULL;
 #ifndef XML_OFF
   (void) epc__xml_init (epc__info);
 #endif
   DBUG_PRINT ("info", ("epc__info: %p", (void *) epc__info));
   DBUG_LEAVE ();
   return epc__info;
 }
References epc__info::connected, epc__xml_init(), epc__info::interfaces, epc__info::interrupt, epc__info::logon, malloc(), epc__info::num_interfaces, epc__info::pipe, epc__info::program, epc__info::purge_pipe, epc__info::sqlca, and epc__info::xml_info.
epc__interrupt()
epc__error_t epc__interrupt (epc__info_t * epc__info)
epc__list_main()
epc__error_t epc__list_main (int argc, char ** argv, epc__interface_t * epc_interface, ...)
Start the EPC for one or more interfaces.
This is usually called from main().
The following command line arguments are recognised:
-D OPTIONS Turn on debugging using the DBUG library.
-I Interrupt the server waiting on the request pipe.
-P Purge the request pipe.
-h Print a help message.
-p REQUEST_PIPE Set the request pipe.
-u USERID Use this connect string for the Oracle logon.
-v Displays the EPC listener version.
Parameters
argc - the number of arguments
argv - the arguments
epc_interface - a NULL terminated list of interfaces
Returns
Definition at line 174 of file lsnr.c.
 {
   char *logon = NULL;
   char *request_pipe = NULL;
   dword_t purge_pipe = 0;
   dword_t interrupt = 0;
   int nr;
   epc__error_t ret;
   /*@only@ *//*@null@ */ epc__info_t *epc__info = NULL;
 #ifndef DBUG_OFF
   /*@only@ *//*@null@ */ char *dbug_options = NULL;
 #endif
   /* process command line parameters */
   for (nr = 0; nr < argc; nr++)
     {
       if (argv[nr][0] == '-')
         {
           switch (argv[nr][1])
             {
 #ifndef DBUG_OFF
             case 'D':
               /* Is it -D... or -D ... */
               if (argv[nr][2] != '\0')
                 {
                   dbug_options = (char *) realloc (dbug_options, strlen (&argv[nr][2]) + 1);
                   assert (dbug_options != NULL);
                   strcpy (dbug_options, &argv[nr][2]);
                 }
               else
                 {
                   ++nr;
                   dbug_options = (char *) realloc (dbug_options, strlen (&argv[nr][0]) + 1);
                   assert (dbug_options != NULL);
                   strcpy (dbug_options, &argv[nr][0]);
                 }
               break;
 #endif
             case 'I':
               interrupt = 1;
               break;
             case 'P':
               purge_pipe = 1;
               break;
             case 'h':
               help (argv[0]);
               return OK;
             case 'p':
               /* Is it -p... or -p ... */
               if (argv[nr][2] != '\0')
                 request_pipe = &argv[nr][2];
               else
                 request_pipe = &argv[++nr][0];
               break;
             case 'u':
               /* Is it -u... or -u ... */
               if (argv[nr][2] != '\0')
                 logon = &argv[nr][2];
               else
                 logon = &argv[++nr][0];
               break;
             case 'v':
               (void) fprintf (stdout, "EPC listener version: %s\n",
                               version ());
               return OK;
             default:
               help (argv[0]);
               return OK;
             }
         }
     }
 #ifndef DBUG_OFF
   /* dmalloc does not want free(NULL), but LCLINT wants free(dbug_options) so malloc 1 byte */
   if (dbug_options == NULL)
     {
       dbug_options = (char *) malloc (1);
       assert (dbug_options != NULL);
       dbug_options[0] = '\0';
     }
 #endif
   assert (OK == 0);
   do
     {
       nr = 0;
 #ifndef DBUG_OFF
       if ((ret = dbug_init (dbug_options, argv[0])) != OK)
         break;
 #endif
       nr++;                     /* 1 */
       epc__info = epc__init ();
       if (epc__info == NULL)
         {
           ret = MEMORY_ERROR;
           break;
         }
       nr++;                     /* 2 */
       epc__info->interrupt = interrupt;
       epc__info->purge_pipe = purge_pipe;
       epc__info->program = argv[0];
       if ((ret = epc__set_logon (epc__info, logon)) != OK)
         break;
       nr++;                     /* 3 */
       if ((ret = epc__set_pipe (epc__info, request_pipe)) != OK)
         break;
       nr++;                     /* 4 */
       {
         va_list ap;
         va_start (ap, epc_interface);
         for (; ret == OK && epc_interface != NULL;)
           {
             ret = epc__add_interface (epc__info, epc_interface);
             epc_interface = va_arg (ap, epc__interface_t *);
           }
         va_end (ap);
       }
       if (ret != OK)
         break;
       nr++;                     /* 5 */
       if ((ret = epc__connect (epc__info)) != OK)
         break;
       nr++;                     /* 6 */
       if ((ret =
            ( epc__info->interrupt == 0
              ? epc__handle_requests (epc__info, epc__recv_request_pipe,
                                      epc__send_response_pipe)
              : epc__interrupt (epc__info) )) != OK)
         break;
       nr++;
     }
   while (0);
   /*@-branchstate@ */
   switch (nr)                   /* last step */
     {
     case 7:
     case 6:
       if (epc__info != NULL) {
         ret = epc__disconnect (epc__info);
       }
       /*@fallthrough@ */
     case 5:
     case 4:
     case 3:
     case 2:
       if (epc__info != NULL) {
         epc__done (epc__info);
       }
       /*@fallthrough@ */
     case 1:
 #ifndef DBUG_OFF
       (void) dbug_done ();
 #endif
       /*@fallthrough@ */
     case 0:
       break;
     default:
       assert (nr >= 0 && nr <= 7);
       break;
     }
   /*@=branchstate@ */
 #ifndef DBUG_OFF
   free (dbug_options);
 #endif
   return ret;
 }
Referenced by epc__main().
epc__lookup_function()
void epc__lookup_function (const char * function_name, epc__info_t * epc__info, epc__call_t * epc__call)
Lookup the function in the list of functions of an interface.
Parameters
function_name The function name
epc__info The EPC run-time information
epc__call The interface member is set if the interface is found. If not found the epc__error member is set to FUNCTION_UNKNOWN.
Definition at line 1690 of file epc_lib.c.
 {
   dword_t fnr;
   int result;
   assert(function_name != NULL);
   epc__call->function = NULL;
   if (epc__call->interface != NULL)
     {
       /* get the function */
       for (fnr = 0;
            fnr < epc__call->interface->num_functions; fnr++)
         if ((result =
              strcmp (function_name,
                      epc__call->interface->functions[fnr].name)) == 0)
           {
             epc__call->function = &epc__call->interface->functions[fnr];
             break;
           }
         else if (result < 0)    /* interface functions sorted ascending */
           {
             break;
           }
     }
   if (epc__call->function == NULL)
     {
       /* interface not found */
       fprintf (stderr, "ERROR: function '%s' not found\n", function_name);
       epc__call->epc__error = FUNCTION_UNKNOWN;
     }
 }
References epc__call::epc__error, epc__call::function, FUNCTION_UNKNOWN, epc__interface::functions, epc__call::interface, epc__function::name, and epc__interface::num_functions.
epc__lookup_interface()
void epc__lookup_interface (const char * interface_name, epc__info_t * epc__info, epc__call_t * epc__call)
Lookup the interface in the list of interfaces.
Parameters
interface_name The interface name
epc__info The EPC run-time information
epc__call The interface member is set if the interface is found. If not found the epc__error member is set to INTERFACE_UNKNOWN.
Definition at line 1648 of file epc_lib.c.
 {
   dword_t inr;
   int result;
   assert (epc__info->interfaces != NULL);
   assert ( interface_name != NULL );
   epc__call->interface = NULL;
   /* get the interface */
   for (inr = 0; inr < epc__info->num_interfaces; inr++)
     if ((result =
          strcmp (interface_name, epc__info->interfaces[inr]->name)) == 0)
       {
         epc__call->interface = epc__info->interfaces[inr];
         break;
       }
     else if (result < 0)        /* interfaces sorted ascending */
       {
         break;
       }
   if (epc__call->interface == NULL)
     {
       /* interface not found */
       fprintf (stderr, "ERROR: interface %s not found\n", interface_name);
       epc__call->epc__error = INTERFACE_UNKNOWN;
     }
 }
References epc__call::epc__error, epc__call::interface, INTERFACE_UNKNOWN, epc__info::interfaces, epc__interface::name, and epc__info::num_interfaces.
epc__main()
epc__error_t epc__main (int argc, char ** argv, epc__interface_t * epc_interface)
Start the EPC for one interface.
See epc__list_main for details.
Parameters
argc - the number of arguments
argv - the arguments
epc_interface - an interface
Returns
Definition at line 145 of file lsnr.c.
 {
   return epc__list_main (argc, argv, epc_interface, NULL);
 }
References epc__list_main().
epc__recv_request_pipe()
epc__error_t epc__recv_request_pipe (epc__info_t * epc__info, epc__call_t * epc__call)
epc__reset_signal_handlers()
void epc__reset_signal_handlers (const int idx)
Definition at line 467 of file epc_lib.c.
 {
   epc__set_signal_handlers (idx);
 }
References epc__set_signal_handlers().
epc__send_response_pipe()
epc__error_t epc__send_response_pipe (epc__info_t * epc__info, epc__call_t * epc__call)
epc__set_handle_interrupt()
void epc__set_handle_interrupt (epc__handle_interrupt_t handle_interrupt, epc__info_t * epc__info)
Definition at line 1621 of file epc_lib.c.
 {
 #ifdef SERVER_INTERRUPT
   G_epc__handle_interrupt = handle_interrupt;
   G_epc__info_interrupt = epc__info;
 #endif
 }
epc__set_logon()
epc__error_t epc__set_logon (epc__info_t * epc__info, char * logon)
Definition at line 834 of file epc_lib.c.
 {
   epc__error_t status = OK;
   DBUG_ENTER ("epc__set_logon");
   DBUG_PRINT ("input", ("epc__info: %p", (void *) epc__info));
   if (epc__info == NULL)
     {
       status = MEMORY_ERROR;
     }
   else if (logon == NULL)
     {
       if (epc__info->logon != NULL)
         {
           free (epc__info->logon);
           epc__info->logon = NULL;
         }
     }
   else
     {
       epc__info->logon =
         (char *) realloc (epc__info->logon, strlen (logon) + 1);
       if (epc__info->logon == NULL)
         status = MEMORY_ERROR;
       else
         strcpy (epc__info->logon, logon);
     }
   DBUG_PRINT ("output", ("status: %d", (int) status));
   DBUG_LEAVE ();
   return (status);
 }
References free(), epc__info::logon, MEMORY_ERROR, and OK.
epc__set_pipe()
epc__error_t epc__set_pipe (epc__info_t * epc__info, char * pipe)
Definition at line 798 of file epc_lib.c.
 {
   epc__error_t status = OK;
   DBUG_ENTER ("epc__set_pipe");
   DBUG_PRINT ("input", ("epc__info: %p; pipe: %s", (void *) epc__info, pipe));
   if (epc__info == NULL)
     {
       status = MEMORY_ERROR;
     }
   else if (pipe == NULL)
     {
       if (epc__info->pipe != NULL)
         {
           free (epc__info->pipe);
           epc__info->pipe = NULL;
         }
     }
   else
     {
       epc__info->pipe = (char *) realloc (epc__info->pipe, strlen (pipe) + 1);
       if (epc__info->pipe == NULL)
         status = MEMORY_ERROR;
       else
         strcpy (epc__info->pipe, pipe);
     }
   DBUG_PRINT ("output", ("status: %d", (int) status));
   DBUG_LEAVE ();
   return (status);
 }
References free(), MEMORY_ERROR, OK, and epc__info::pipe.
epc__set_signal_handlers()
void epc__set_signal_handlers (const int idx)
Definition at line 339 of file epc_lib.c.
 {
 #ifdef SERVER_INTERRUPT
   int nr;
 #endif
   DBUG_ENTER ("epc__set_signal_handlers");
 #ifdef SERVER_INTERRUPT
   for (nr = 0; nr < MAX_SIGNO; nr++)
     {
       /* GJP 16-02-2009
          Some defined signals may have the same number hence a switch will not compile.
       */
       if (0
 #ifdef SIGHUP
           || (nr == SIGHUP)
 #endif
 #ifdef SIGQUIT
           || (nr == SIGQUIT)
 #endif
 #ifdef SIGILL
           || (nr == SIGILL)
 #endif
 #ifdef SIGTRAP
           || (nr == SIGTRAP)
 #endif
 #ifdef SIGABRT
           || (nr == SIGABRT)
 #endif
 #ifdef SIGEMT
           || (nr == SIGEMT)
 #endif
 #ifdef SIGFPE
           || (nr == SIGFPE)
 #endif
 #ifdef SIGBUS
           || (nr == SIGBUS)
 #endif
 #ifdef SIGSEGV
           || (nr == SIGSEGV)
 #endif
 #ifdef SIGSYS
           || (nr == SIGSYS)
 #endif
 #ifdef SIGPIPE
           || (nr == SIGPIPE)
 #endif
 #ifdef SIGALRM
           || (nr == SIGALRM)
 #endif
 #ifdef SIGTERM
           || (nr == SIGTERM)
 #endif
 #ifdef SIGURG
           || (nr == SIGURG)
 #endif
 #ifdef SIGSTOP
           || (nr == SIGSTOP)
 #endif
 #ifdef SIGTSTP
           || (nr == SIGTSTP)
 #endif
 #ifdef SIGCONT
           || (nr == SIGCONT)
 #endif
 #ifdef SIGCHLD
           || (nr == SIGCHLD)
 #endif
 #ifdef SIGTTIN
           || (nr == SIGTTIN)
 #endif
 #ifdef SIGTTOU
           || (nr == SIGTTOU)
 #endif
 #ifdef SIGIO
           || (nr == SIGIO)
 #endif
 #ifdef SIGXCPU
           || (nr == SIGXCPU)
 #endif
 #ifdef SIGXFSZ
           || (nr == SIGXFSZ)
 #endif
 #ifdef SIGVTALRM
           || (nr == SIGVTALRM)
 #endif
 #ifdef SIGPROF
           || (nr == SIGPROF)
 #endif
 #ifdef SIGWINCH
           || (nr == SIGWINCH)
 #endif
 #ifdef SIGLOST
           || (nr == SIGLOST)
 #endif
 #ifdef SIGUSR1
           || (nr == SIGUSR1)
 #endif
 #ifdef SIGUSR2
           || (nr == SIGUSR2)
 #endif
 #ifdef SIGBREAK
           || (nr == SIGBREAK)
 #endif
           )
         {
           DBUG_PRINT ("info", ("handler for signal %d (%s): %p",
                                nr,
                                signal_str (nr),
                                signal_handler_info[idx][nr].func));
           /* store old handler */
           signal_handler_info[idx][nr].func =
             signal (nr, signal_handler_info[idx][nr].func);
         }
       else
         {
           /* SIGINT or other */
           continue;             /* GJP 21-02-2004 Handled by handle_interrupt() */
         }
     }
 #endif /* #ifdef SERVER_INTERRUPT */
   DBUG_LEAVE ();
 }
Referenced by epc__reset_signal_handlers().