epc: epc_xml.c File Reference
epc_xml.c File Reference
#include <stdlib.h>
#include <dbug.h>
#include <oratypes.h>
#include <oraxml.h>
#include "epc_xml.h"
#include "epc_lib.h"
#include "epc.h"
Classes
struct _int64
struct epc__xml_ctx_t
struct xml_info
Macros
#define string_defined
#define LEVEL_SOAP_ENVELOPE 1
#define LEVEL_SOAP_BODY 2
#define LEVEL_SOAP_METHOD 3
#define LEVEL_SOAP_ARGUMENT 4
#define LEVEL_XMLRPC_METHOD 2
#define LEVEL_XMLRPC_ARGUMENT 5
Typedefs
typedef struct xml_info xml_info_t
Functions
unsigned int epc__xml_init (epc__info_t *epc__info)
Initialize the SAX XML parser.
unsigned int epc__xml_done (epc__info_t *epc__info)
Terminate the SAX XML parser.
unsigned int epc__xml_parse (epc__info_t *epc__info, epc__call_t *epc__call, const char *buf, const size_t len)
Parse an XML buffer.
Macro Definition Documentation
LEVEL_SOAP_ARGUMENT
#define LEVEL_SOAP_ARGUMENT 4
Definition at line 61 of file epc_xml.c.
LEVEL_SOAP_BODY
#define LEVEL_SOAP_BODY 2
Definition at line 59 of file epc_xml.c.
LEVEL_SOAP_ENVELOPE
#define LEVEL_SOAP_ENVELOPE 1
Definition at line 58 of file epc_xml.c.
LEVEL_SOAP_METHOD
#define LEVEL_SOAP_METHOD 3
Definition at line 60 of file epc_xml.c.
LEVEL_XMLRPC_ARGUMENT
#define LEVEL_XMLRPC_ARGUMENT 5
Definition at line 110 of file epc_xml.c.
LEVEL_XMLRPC_METHOD
#define LEVEL_XMLRPC_METHOD 2
Definition at line 109 of file epc_xml.c.
string_defined
#define string_defined
Definition at line 48 of file epc_xml.c.
Typedef Documentation
xml_info_t
typedef struct xml_info xml_info_t
Function Documentation
epc__xml_done()
unsigned int epc__xml_done (epc__info_t * epc__info)
Terminate the SAX XML parser.
Terminates the SAX XML parser. The callback information is freed.
Parameters
epc__info Epc run-time information.
Returns
error code returned by xmlterm
Definition at line 243 of file epc_xml.c.
 {
   uword ecode = XMLERR_OK;
   xml_info_t *xml_info = (xml_info_t *) epc__info->xml_info;
   DBUG_ENTER ("epc__xml_done");
   assert (xml_info != NULL);
   DBUG_PRINT ("info", ("xmlctx: %p", xml_info->xmlctx));
   ecode = xmlterm (xml_info->xmlctx);   /* terminate XML package */
   xml_info->epc__xml_ctx.epc__info = NULL;
   free (xml_info);
   epc__info->xml_info = NULL;
   DBUG_LEAVE ();
   return ecode;
 }
References epc__xml_ctx_t::epc__info, xml_info::epc__xml_ctx, free(), epc__info::xml_info, and xml_info::xmlctx.
Referenced by epc__done().
epc__xml_init()
unsigned int epc__xml_init (epc__info_t * epc__info)
Initialize the SAX XML parser.
Set-up the SAX XML parser. The callback information is stored in the heap in order to prevent a stack dump.
Parameters
epc__info Epc run-time information.
Returns
error code returned by xmlinit
Definition at line 171 of file epc_xml.c.
 {
   uword ecode = 0;
   /*@-nullassign@ */
   const xmlsaxcb saxcb = {
     start_document,
     end_document,
     NULL,
     end_element,
     element_content,
     NULL,
     NULL,
     NULL,
     NULL,
     start_element,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL
   };
   /*@=nullassign@ */
   /*@only@ */ xml_info_t *xml_info;
   DBUG_ENTER ("epc__xml_init");
   assert (epc__info->xml_info == NULL);
   xml_info = (xml_info_t *) malloc (sizeof (xml_info_t));
   assert (xml_info != NULL);
   xml_info->epc__xml_ctx.epc__info = epc__info;
   xml_info->epc__xml_ctx.epc__call = NULL;
   xml_info->epc__xml_ctx.num_parameters = 0L;
   xml_info->epc__xml_ctx.level = 0;
   xml_info->saxcb = saxcb;
   /*@-nullpass@ */
   xml_info->xmlctx = xmlinit (&ecode,
                               NULL,
                               error_handler,
                               &xml_info->epc__xml_ctx,
                               &xml_info->saxcb,
                               &xml_info->epc__xml_ctx, NULL, NULL, NULL);
   /*@=nullpass@ */
   DBUG_PRINT ("info", ("xmlctx: %p", xml_info->xmlctx));
   DBUG_LEAVE ();
   epc__info->xml_info = xml_info;
   assert (epc__info->xml_info != NULL);
   return ecode;
 }
Referenced by epc__init().
epc__xml_parse()
unsigned int epc__xml_parse (epc__info_t * epc__info, epc__call_t * epc__call, const char * buf, const size_t len)
Parse an XML buffer.
Parameters
epc__info Epc run-time information.
epc__call Epc call information.
buf XML buffer.
len XML buffer length (excluding terminating zero).
Returns
error code returned by xmlparsebuf
Definition at line 276 of file epc_xml.c.
 {
   uword ecode = XMLERR_OK;
   ub4 flags = XML_FLAG_DISCARD_WHITESPACE;      /* | XML_FLAG_VALIDATE; */
   xml_info_t *xml_info = (xml_info_t *) epc__info->xml_info;
   DBUG_ENTER ("epc__xml_parse");
   assert (xml_info != NULL);
   DBUG_PRINT ("info", ("xmlctx: %p", xml_info->xmlctx));
   DBUG_PRINT ("input", ("buf: %*s", len, buf));
   xml_info->epc__xml_ctx.epc__call = epc__call;
   /*@-nullpass@ */
   ecode = xmlparsebuf (xml_info->xmlctx, (oratext *) buf, len, NULL, flags);
   /*@=nullpass@ */
   xmlclean (xml_info->xmlctx);
   DBUG_PRINT ("output", ("ecode: %lu", (unsigned long) ecode));
   DBUG_LEAVE ();
   return ecode;
 }
References epc__xml_ctx_t::epc__call, xml_info::epc__xml_ctx, epc__info::xml_info, and xml_info::xmlctx.