whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on

prompt @@V0001__TYPE_SPEC.STD_OBJECT.sql
@@V0001__TYPE_SPEC.STD_OBJECT.sql
prompt @@V0002__TYPE_SPEC.EPC_CLNT_OBJECT.sql
@@V0002__TYPE_SPEC.EPC_CLNT_OBJECT.sql
prompt @@V0003__TABLE.STD_OBJECTS.sql
@@V0003__TABLE.STD_OBJECTS.sql
prompt @@R__09.PACKAGE_SPEC.EPC.sql
prompt @@V0004__INDEX.STD_OBJECTS.sql
@@V0004__INDEX.STD_OBJECTS.sql
prompt @@V0005__CONSTRAINT.STD_OBJECTS.sql
@@V0005__CONSTRAINT.STD_OBJECTS.sql
@@R__09.PACKAGE_SPEC.EPC.sql
prompt @@R__09.PACKAGE_SPEC.EPC_CLNT.sql
@@R__09.PACKAGE_SPEC.EPC_CLNT.sql
prompt @@R__09.PACKAGE_SPEC.EPC_SRVR.sql
@@R__09.PACKAGE_SPEC.EPC_SRVR.sql
prompt @@R__09.PACKAGE_SPEC.STD_OBJECT_MGR.sql
@@R__09.PACKAGE_SPEC.STD_OBJECT_MGR.sql
prompt @@R__14.PACKAGE_BODY.EPC.sql
@@R__14.PACKAGE_BODY.EPC.sql
prompt @@R__14.PACKAGE_BODY.EPC_CLNT.sql
@@R__14.PACKAGE_BODY.EPC_CLNT.sql
prompt @@R__14.PACKAGE_BODY.EPC_SRVR.sql
@@R__14.PACKAGE_BODY.EPC_SRVR.sql
prompt @@R__14.PACKAGE_BODY.STD_OBJECT_MGR.sql
@@R__14.PACKAGE_BODY.STD_OBJECT_MGR.sql
prompt @@R__15.TYPE_BODY.EPC_CLNT_OBJECT.sql
@@R__15.TYPE_BODY.EPC_CLNT_OBJECT.sql
prompt @@R__15.TYPE_BODY.STD_OBJECT.sql
@@R__15.TYPE_BODY.STD_OBJECT.sql
